---
- name: Blocks Install Apache and Start Service
  gather_facts: false
  hosts: webservers
  tasks:
    - name: Just execute command
      shell: ls -1 /tmp

    - name: Start Firewall service 
      block:
        - name:  Open http service on OS firewall 
          firewalld: 
            service: http
            permanent: yes
            state: enabled

        - name:  Open http service on OS firewall 
          firewalld: 
            port: 80/tcp
            permanent: yes
            state: enabled

    - name: Install block
      block:
        - name: Install httpd package
          yum:
            name: httpd
            state: latest
        
        
        - name: Copy index file
          copy:
            src: files/not_existing_file_index.html
            dest: /var/www/html/index.html
          register: copy_output
        
        - name: Start httpd service
          service:
            name: httpd
            state: restarted
            enabled: yes
          when: copy_output.changed
      rescue:
        - name: New block
          block:
            - name: Rescue block error message
              shell: echo "Apache kurulurken hata alinmistir"
              register: echo_output
              failed_when: "'hata alinmistir' in echo_output.stdout"
          rescue:
            - name: Inner rescue
              debug:
                msg: "Icteki rescue task tetiklenmistir."
      always:
        - name: End of play
          debug:
            msg: "Playbook tasklari tamamlanmistir."

